default_k: 1.0
sample_rate: 1000
duration: 1.0
output_dir: "output"
k: 1.0
charge: 1.0
frequency: 5.0
mass: 1.0
theta: 0         # degrees
medium_scale: 1.0
duration: 1.0     # seconds
waveform: sine
sample_rate: 1000
